"""
Final report generation.

The report is written as Markdown, which is what gets stored in MySQL and what
the user downloads. The on-screen report page renders the same content from the
results dictionary with the site's styling.

It is written for two readers at once: the executive summary and the objective
section avoid jargon entirely, while the sections below them carry the numbers
a technical reviewer will look for.
"""

from datetime import datetime


def _line(label, value):
    return f"- **{label}:** {value}"


def _table(headers, rows):
    lines = ["| " + " | ".join(headers) + " |",
             "|" + "|".join(["---"] * len(headers)) + "|"]
    for row in rows:
        lines.append("| " + " | ".join(str(cell) for cell in row) + " |")
    return "\n".join(lines)


def _format_metric(name, value):
    if value is None:
        return "n/a"
    if name in ("mae", "mse", "rmse"):
        return f"{value:,.4f}"
    return f"{value:.4f}"


def build_markdown(results, dataset_name):
    """Turn a completed analysis into the full Markdown report."""
    status = results.get("status")
    generated = datetime.now().strftime("%d %B %Y at %H:%M")

    parts = [
        "# Data Science Report",
        "",
        f"*Generated by Data Scientist Agent 2.0 on {generated}*",
        "",
        _line("Dataset", dataset_name),
        _line("Objective", f'"{results.get("objective", "")}"'),
        _line("Reasoning layer",
              "Google Gemini" if results.get("ai_source") == "gemini"
              else "Built-in rule-based analyst (no Gemini API key configured)"),
        "",
    ]

    # ------------------------------------------------ not a modelling run ---
    if status in ("exploratory", "unsupported"):
        parts += [
            "## Executive summary",
            "",
            results.get("explanation", ""),
            "",
            _describe_dataset(results),
            "",
            _describe_quality(results),
            "",
            _describe_cleaning(results),
            "",
            "## Limitations",
            "",
            "No predictive model was trained for this objective, so no accuracy figure is "
            "reported. Any number in this report describes the data as it stands, not a "
            "prediction about future data.",
            "",
        ]
        return "\n".join(parts)

    if status != "completed":
        parts += ["## Analysis did not complete", "", results.get("error", "Unknown error."), ""]
        return "\n".join(parts)

    best = results["best"]
    validation = results["objective_validation"]
    metric = results["metric"]

    # ----------------------------------------------------------- summary ---
    parts += [
        "## Executive summary",
        "",
        f"The objective was to {results['objective'].rstrip('.').lower()}. "
        f"The agent identified this as a **{results['problem_type']}** problem predicting "
        f"**{results['target_column']}**, trained "
        f"{len([r for r in results['model_results'] if r['status'] == 'trained'])} models and "
        f"selected **{best['model_name']}**, which scored "
        f"**{_format_metric(metric, best['primary_score'])} {metric.upper()}** on data it had "
        f"never seen.",
        "",
        f"**Objective status: {validation['status']}**",
        "",
        validation["reason"],
        "",
    ]

    # ------------------------------------------------------------- data ----
    parts += [_describe_dataset(results), "", _describe_quality(results), "",
              _describe_cleaning(results), ""]

    # -------------------------------------------------- problem framing ----
    parts += [
        "## Problem type and target variable",
        "",
        _line("Problem type", f"{results['problem_type'].title()} — {results['problem_type_reason']}"),
        _line("Target variable", f"`{results['target_column']}`"),
        _line("Confidence in the target", f"{results['target_confidence']:.0%}"),
        _line("Evaluation metric", f"{metric.upper()} — {results['metric_reason']}"),
        _line("Train/test split", f"{results['split_note']} "
                                  f"{results['train_rows']:,} training rows, "
                                  f"{results['test_rows']:,} test rows."),
        "",
    ]

    # ---------------------------------------------------- preprocessing ----
    parts += [
        "## Preprocessing",
        "",
        "Preprocessing runs inside a scikit-learn pipeline that is fitted on the training "
        "split only, so no information from the test rows can influence it.",
        "",
        "- Numeric columns: missing values filled with the training median; scaled for the "
        "linear and distance-based models that need it.",
        "- Categorical columns: missing values filled with the most frequent training value, "
        "then one-hot encoded with rare categories grouped.",
        "- Unseen categories at prediction time are ignored rather than causing an error.",
        "",
    ]

    # ------------------------------------------------------ engineering ----
    created = results["engineering"]["created"]
    parts += ["## Feature engineering", ""]
    if created:
        parts += [f"{len(created)} feature(s) were derived from the original columns:", "",
                  _table(["Feature", "Built from", "Type", "Why"],
                         [(f"`{c['name']}`", c["source"], c["type"], c["reason"])
                          for c in created]),
                  ""]
    else:
        parts += ["No derived features were needed; the original columns were used as they are.", ""]

    # ------------------------------------------------------- selection -----
    selection = results["selection"]
    parts += [
        "## Feature selection",
        "",
        f"{len(selection['kept'])} feature(s) were kept and {len(selection['removed'])} removed.",
        "",
        "**Kept:** " + ", ".join(f"`{f}`" for f in selection["kept"]),
        "",
    ]
    if selection["removed"]:
        parts += ["**Removed:**", "",
                  _table(["Feature", "Reason"],
                         [(f"`{r['feature']}`", r["reason"]) for r in selection["removed"]]),
                  ""]
    if selection["leakage"]:
        parts += [
            "### Target leakage detected",
            "",
            "The following columns predicted the target so well that they were almost certainly "
            "derived from it. Leaving them in would have produced an impressive score that "
            "collapses on real data, so they were removed:",
            "",
            _table(["Column", "Evidence"],
                   [(f"`{l['feature']}`", l["evidence"]) for l in selection["leakage"]]),
            "",
        ]

    # ---------------------------------------------------------- models -----
    trained = [r for r in results["model_results"] if r["status"] == "trained"]
    failed = [r for r in results["model_results"] if r["status"] == "failed"]

    parts += ["## Models evaluated", ""]
    if results["problem_type"] == "classification":
        headers = ["Model", "Accuracy", "Precision", "Recall", "F1", "ROC-AUC", "Time (s)"]
        rows = [
            (r["model_name"] + (" *(baseline)*" if r["is_baseline"] else ""),
             _format_metric("accuracy", r["metrics"].get("accuracy")),
             _format_metric("precision", r["metrics"].get("precision")),
             _format_metric("recall", r["metrics"].get("recall")),
             _format_metric("f1", r["metrics"].get("f1")),
             _format_metric("roc_auc", r["metrics"].get("roc_auc")),
             r["train_time_sec"])
            for r in trained
        ]
    else:
        headers = ["Model", "R²", "RMSE", "MAE", "MSE", "Time (s)"]
        rows = [
            (r["model_name"] + (" *(baseline)*" if r["is_baseline"] else ""),
             _format_metric("r2", r["metrics"].get("r2")),
             _format_metric("rmse", r["metrics"].get("rmse")),
             _format_metric("mae", r["metrics"].get("mae")),
             _format_metric("mse", r["metrics"].get("mse")),
             r["train_time_sec"])
            for r in trained
        ]
    parts += [_table(headers, rows), ""]

    if results.get("models_rejected"):
        parts += ["Models the AI suggested but the agent refused to run:", "",
                  _table(["Suggested", "Why it was not used"],
                         [(r["name"], r["reason"]) for r in results["models_rejected"]]), ""]
    if failed:
        parts += ["Models that failed during training:", "",
                  _table(["Model", "Error"],
                         [(r["model_name"], r["error_message"]) for r in failed]), ""]

    # ------------------------------------------------------ best model -----
    parts += [
        "## Best model",
        "",
        _line("Model", best["model_name"]),
        _line("Headline score", f"{_format_metric(metric, best['primary_score'])} ({metric.upper()})"),
        _line("Why this model", best.get("selection_reason", "")),
        "",
    ]
    if results.get("baseline_score") is not None:
        parts += [_line("Naive baseline", f"{_format_metric(metric, results['baseline_score'])} "
                                          f"— the score to beat before a model means anything"), ""]
    if results.get("cross_validation"):
        cv = results["cross_validation"]
        parts += [_line("Cross-validated", f"{cv['mean']:.4f} ± {cv['std']:.4f} over "
                                           f"{cv['folds']} folds"), ""]

    parts += ["### Full metrics for the selected model", ""]
    detail_rows = [(k.replace("_", " ").title(), _format_metric(k, v))
                   for k, v in best["metrics"].items()
                   if isinstance(v, (int, float)) or v is None]
    parts += [_table(["Metric", "Value"], detail_rows), ""]

    if results["problem_type"] == "classification" and best["metrics"].get("per_class"):
        parts += ["### Performance on each class", "",
                  _table(["Class", "Rows in test set", "Correctly identified"],
                         [(label, info["support"], f"{info['recall']:.1%}")
                          for label, info in best["metrics"]["per_class"].items()]), ""]

    # ------------------------------------------------------ importance -----
    importance = results.get("importance") or {}
    if importance.get("features"):
        parts += [
            "## What drives the predictions",
            "",
            f"*{importance.get('method')}: {importance.get('explanation', '')}*",
            "",
            _table(["Rank", "Feature", "Share of total importance"],
                   [(i + 1, f"`{f['feature']}`", f"{f['share']:.1f}%")
                    for i, f in enumerate(importance["features"])]),
            "",
        ]

    # ------------------------------------------------------- objective -----
    parts += [
        "## Did the analysis meet the objective?",
        "",
        f"**{validation['status']}**",
        "",
        "Model performance and objective fulfilment are separate questions. A model can score "
        "well and still fail the objective. Each check below was applied independently:",
        "",
        _table(["Check", "Result", "Detail"],
               [(c["name"],
                 {True: "Pass", False: "Fail", "partial": "Partial"}.get(c["passed"], "—"),
                 c["detail"]) for c in validation["checks"]]),
        "",
    ]

    # --------------------------------------------------------- insights ----
    if results.get("insights"):
        parts += ["## Key insights", ""] + [f"- {text}" for text in results["insights"]] + [""]

    # ------------------------------------------------------ limitations ----
    parts += ["## Limitations", ""]
    limitations = [
        "Scores are measured on a single random hold-out split of this dataset. Performance on "
        "genuinely new data collected later can differ.",
        "No hyperparameter search was performed; every model used sensible defaults.",
        "The agent applies general statistical rules and has no domain knowledge about what "
        "these columns mean in your business.",
    ]
    if results.get("sampled"):
        limitations.append("The dataset was sampled down before training, so a larger run could "
                           "produce different results.")
    if results["profile_after"]["n_rows"] < 1000:
        limitations.append(f"Only {results['profile_after']['n_rows']:,} rows were available, "
                           f"which is a small sample for reliable conclusions.")
    for warning in results.get("warnings", []):
        limitations.append(warning)
    parts += [f"- {text}" for text in limitations] + [""]

    # -------------------------------------------------- recommendations ----
    if results.get("recommendations"):
        parts += ["## Recommended next steps", ""]
        parts += [f"{i + 1}. {text}" for i, text in enumerate(results["recommendations"])]
        parts += [""]

    # ------------------------------------------------------ AI comments ----
    recommendation = results.get("recommendation") or {}
    if recommendation.get("reasoning"):
        parts += ["## AI analyst commentary", "", recommendation["reasoning"], ""]
    if recommendation.get("preprocessing_recommendations"):
        parts += ["**Preprocessing suggested by the AI layer:**", ""]
        parts += [f"- {t}" for t in recommendation["preprocessing_recommendations"]] + [""]
    if recommendation.get("corrections"):
        parts += [
            "**Corrections the agent applied to the AI's answer:**",
            "",
            "Every AI recommendation is validated against the real dataset before it is acted on. "
            "These suggestions did not survive that check:",
            "",
        ]
        parts += [f"- {t}" for t in recommendation["corrections"]] + [""]

    parts += ["---", "",
              "*This report was produced automatically. Review the findings with someone who "
              "knows the data before making decisions based on them.*", ""]

    return "\n".join(parts)


# --------------------------------------------------------------------------
# Shared section builders
# --------------------------------------------------------------------------

def _describe_dataset(results):
    profile = results.get("profile_before") or {}
    if not profile:
        return ""
    return "\n".join([
        "## Dataset overview",
        "",
        _line("Rows", f"{profile['n_rows']:,}"),
        _line("Columns", profile["n_columns"]),
        _line("Numeric columns", len(profile["numeric_columns"])),
        _line("Categorical columns", len(profile["categorical_columns"])),
        _line("Date columns", len(profile["datetime_columns"])),
        _line("Duplicate rows", f"{profile['duplicate_rows']:,} ({profile['duplicate_pct']}%)"),
        _line("Missing cells", f"{profile['total_missing_cells']:,} ({profile['missing_pct']}% of all cells)"),
        _line("Size in memory", f"{profile['memory_mb']} MB"),
    ])


def _describe_quality(results):
    profile = results.get("profile_before") or {}
    if not profile:
        return ""
    lines = [
        "## Data quality",
        "",
        f"**Quality score: {profile['quality_score']}/100**",
        "",
    ]
    lines += [f"- {issue['message']}" for issue in profile["quality_issues"]]
    return "\n".join(lines)


def _describe_cleaning(results):
    report = results.get("cleaning") or {}
    if not report:
        return ""
    before, after = report["before"], report["after"]
    lines = [
        "## Cleaning performed",
        "",
        _table(["", "Before", "After"],
               [["Rows", f"{before['rows']:,}", f"{after['rows']:,}"],
                ["Columns", before["columns"], after["columns"]],
                ["Missing cells", f"{before['missing_cells']:,}", f"{after['missing_cells']:,}"],
                ["Duplicate rows", f"{before['duplicate_rows']:,}", f"{after['duplicate_rows']:,}"]]),
        "",
    ]
    if report["steps"]:
        lines += [f"- **{step['action']}.** {step['detail']}" for step in report["steps"]]
        lines += [""]
    lines += [f"*{report['missing_note']}*"]
    return "\n".join(lines)
